# Pandas Grouping and Aggregation Demo
This notebook demonstrates how to use the `.groupby()` and `.agg()` functions to summarize data efficiently.

In [42]:
import pandas as pd

# Creating a sample dataset
data = {
    'Department': ['Sales', 'Sales', 'IT', 'IT', 'HR', 'Sales', 'IT', 'HR'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Edward', 'Fiona', 'George', 'Hannah'],
    'Salary': [70000, 80000, 90000, 85000, 60000, 75000, 95000, 65000],
    'Experience_Years': [5, 7, 3, 4, 2, 6, 8, 3]
}

df = pd.DataFrame(data)
df

  Department Employee  Salary  Experience_Years
0      Sales    Alice   70000                 5
1      Sales      Bob   80000                 7
2         IT  Charlie   90000                 3
3         IT    David   85000                 4
4         HR   Edward   60000                 2
5      Sales    Fiona   75000                 6
6         IT   George   95000                 8
7         HR   Hannah   65000                 3

In [43]:
df['Salary'].mean()

np.float64(77500.0)

### 1. Basic Grouping
Calculate the mean salary for each department.

In [44]:
df.groupby('Department')['Salary']

In [45]:
avg_salary = df.groupby('Department')['Salary'].mean()
print(avg_salary)

Department
HR       62500.0
IT       90000.0
Sales    75000.0
Name: Salary, dtype: float64

### 2. Multiple Aggregations
You can perform multiple calculations at once using `.agg()`.

In [70]:
summary = df.groupby('Department').agg({
    'Salary': ['mean', 'max'],
    'Experience_Years': 'sum'
})

# hierarchical index
# summary['Salary']['mean'].loc['HR']
summary

             Salary        Experience_Years
               mean    max              sum
Department
HR          62500.0  65000                5
IT          90000.0  95000               15
Sales       75000.0  80000               18

### stacking and unstacking

In [80]:
ss = summary.stack().stack()
ss
# ss.index

# # ss.loc['HR'].loc['max']
# ss.loc[('HR','max')]

C:\Users\David\AppData\Local\Temp\ipykernel_26864\1590604308.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  ss = summary.stack().stack()

Department
HR          max   Salary              65000.0
            mean  Salary              62500.0
            sum   Experience_Years        5.0
IT          max   Salary              95000.0
            mean  Salary              90000.0
            sum   Experience_Years       15.0
Sales       max   Salary              80000.0
            mean  Salary              75000.0
            sum   Experience_Years       18.0
dtype: float64

### 3. Named Aggregation
This is a cleaner way to rename your columns while aggregating.

In [81]:
named_agg = df.groupby('Department').agg(
    total_payroll=('Salary', 'sum'),
    average_experience=('Experience_Years', 'mean')
)
named_agg

            total_payroll  average_experience
Department
HR                 125000                 2.5
IT                 270000                 5.0
Sales              225000                 6.0