# Data Binning with Pandas
Binning allows us to group continuous data into intervals. This notebook covers:
1. **Fixed-width binning** (Defining your own edges)
2. **Equal-width binning** (Automatic linear splitting)
3. **Quantile binning** (Equal number of observations per bin)

In [1]:
import pandas as pd
import numpy as np

# Sample data: Exam scores for 12 students
df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L'],
    'Score': [45, 55, 62, 72, 78, 81, 85, 88, 91, 95, 98, 100]
})
df

   Student  Score
0        A     45
1        B     55
2        C     62
3        D     72
4        E     78
5        F     81
6        G     85
7        H     88
8        I     91
9        J     95
10       K     98
11       L    100

### 1. Fixed-Width Binning (pd.cut)
Assigning custom letter grades based on specific score ranges.

In [2]:
bins = [0, 60, 75, 90, 100]
labels = ['Fail', 'C', 'B', 'A']

df['Grade'] = pd.cut(df['Score'], bins=bins, labels=labels)
df

   Student  Score Grade
0        A     45  Fail
1        B     55  Fail
2        C     62     C
3        D     72     C
4        E     78     B
5        F     81     B
6        G     85     B
7        H     88     B
8        I     91     A
9        J     95     A
10       K     98     A
11       L    100     A

### 2. Equal-Width Binning
Pandas calculates the edges automatically to create 3 bins of equal range length.

In [3]:
df['Range_Group'] = pd.cut(df['Score'], bins=3)
df.groupby('Range_Group').size()

C:\Users\David\AppData\Local\Temp\ipykernel_28444\2756022708.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Range_Group').size()

Range_Group
(44.945, 63.333]    3
(63.333, 81.667]    3
(81.667, 100.0]     6
dtype: int64

### 3. Equal-Frequency Binning (pd.qcut)
Splitting data so each bin has the same number of data points (Quantiles).

In [4]:
df['Quantile_Group'] = pd.qcut(df['Score'], q=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
df

   Student  Score Grade       Range_Group Quantile_Group
0        A     45  Fail  (44.945, 63.333]             Q1
1        B     55  Fail  (44.945, 63.333]             Q1
2        C     62     C  (44.945, 63.333]             Q1
3        D     72     C  (63.333, 81.667]             Q2
4        E     78     B  (63.333, 81.667]             Q2
5        F     81     B  (63.333, 81.667]             Q2
6        G     85     B   (81.667, 100.0]             Q3
7        H     88     B   (81.667, 100.0]             Q3
8        I     91     A   (81.667, 100.0]             Q3
9        J     95     A   (81.667, 100.0]             Q4
10       K     98     A   (81.667, 100.0]             Q4
11       L    100     A   (81.667, 100.0]             Q4