In [1]:
import pandas as pd
import numpy as np
import difflib

# require pip installs
from thefuzz import process 
from faker import Faker
fake = Faker()

In [2]:
n = 100

names = [fake.first_name() for _ in range(n)]
salaries = np.random.exponential(scale=20000, size=n) + 30000

fd1 = pd.DataFrame({
    "Name":names,
    "Salary":salaries
})
fd1.shape

(100, 2)

## split and concat

In [3]:
fd1_a = fd1.loc[:49]    # slicing is INCLUSIVE here
fd1_b = fd1.loc[50:]

print(fd1_a.shape,
      fd1_b.shape)

fd1_a.tail()

(50, 2) (50, 2)

       Name         Salary
45   Dustin   79693.374910
46    Laura   33366.564949
47   Briana   35395.052404
48    Andre   70952.057471
49  Michael  105816.382715

In [4]:
fd1_ab = pd.concat([fd1_a,fd1_b])
fd1_ab.shape

(100, 2)

## Merge

* use merge to combine columns from two or more dataframes

In [5]:
# use the same names as before

mu = 70     # mean
sigma = 2.75    # stdev
heights = np.random.normal(loc=mu, scale=sigma, size=n)

fd2 = pd.DataFrame({
    "Name":names,
    "Height":heights
})
fd2.shape

(100, 2)

In [6]:
print(fd1.head())
print("---")
print(fd2.head())

          Name        Salary
0       Nathan  36002.016244
1          Amy  62807.063516
2        Emily  64032.703825
3       Meagan  36817.289292
4  Christopher  35323.130648
---
          Name     Height
0       Nathan  72.936875
1          Amy  73.690252
2        Emily  68.436012
3       Meagan  68.614862
4  Christopher  74.428719

in this case, we could just add the column, or concatenate

In [7]:
# # add the column
# fd1['Height'] = fd2['Height']
# fd1.head()

# # concatenate
# pd.concat([fd1,fd2['Height']],axis = 'columns')

but this will only work if the rows line up perfectly

In [8]:
# left_on and right_on are only needed if the columns your using to match have different names
fd_merged = pd.merge(fd1,fd2, left_on="Name", right_on="Name")
fd_merged.head()

     Name        Salary     Height
0  Nathan  36002.016244  72.936875
1  Nathan  36002.016244  69.354040
2     Amy  62807.063516  73.690252
3     Amy  62807.063516  64.902345
4   Emily  64032.703825  68.436012