In [1]:
import pandas as pd
import numpy as np

from faker import Faker
fake = Faker()

In [2]:
n = 100

names = [fake.first_name() for _ in range(n)]
salaries = np.random.exponential(scale=20000, size=n) + 30000

fd1 = pd.DataFrame({
    "Name":names,
    "Salary":salaries
})
fd1.head()
# fd1.shape

          Name        Salary
0        Wanda  65369.444472
1      William  38113.892281
2       Taylor  84802.019656
3  Christopher  72232.744720
4       Andrew  45306.997032

## split and concat

In [3]:
fd1_a = fd1.loc[:49]    # slicing is INCLUSIVE here
fd1_b = fd1.loc[50:]

print(fd1_a.shape,
      fd1_b.shape)

fd1_a.tail()

(50, 2) (50, 2)

       Name        Salary
45     Kari  63819.142522
46    Erica  51534.702247
47   Andrew  41489.035678
48  Douglas  44903.537981
49  Kristin  39270.426271

now concatenate to put them back together

In [4]:
fd1_ab = pd.concat([fd1_a,fd1_b])
fd1_ab.shape

(100, 2)

## Merge

* use merge to combine columns from two or more dataframes

In [5]:
# use the same names as before

mu = 70     # mean
sigma = 2.75    # stdev
heights = np.random.normal(loc=mu, scale=sigma, size=n)

fd2 = pd.DataFrame({
    "Name":names,
    "Height":heights
})
fd2.shape

(100, 2)

In [6]:
print(fd1.head())
print("---")
print(fd2.head())

          Name        Salary
0        Wanda  65369.444472
1      William  38113.892281
2       Taylor  84802.019656
3  Christopher  72232.744720
4       Andrew  45306.997032
---
          Name     Height
0        Wanda  69.788546
1      William  71.109718
2       Taylor  68.017695
3  Christopher  69.391021
4       Andrew  67.120143

in this case, we could just add the column, or concatenate

In [7]:
# # add the column
# fd1['Height'] = fd2['Height']
# fd1.head()

# # concatenate
# pd.concat([fd1,fd2['Height']],axis = 'columns')

but this will only work if the rows line up perfectly

In [8]:
# left_on and right_on are only needed if the columns your using to match have different names
fd_merged = pd.merge(fd1,fd2, left_on="Name", right_on="Name")
fd_merged.head()

      Name        Salary     Height
0    Wanda  65369.444472  69.788546
1  William  38113.892281  71.109718
2  William  38113.892281  75.895364
3   Taylor  84802.019656  68.017695
4   Taylor  84802.019656  72.018622