# 🐼 Pandas Essentials: A Quick-Start Guide

Pandas is the bread and butter of Python data analysis. This notebook covers the core operations you'll use 90% of the time.

In [1]:
import pandas as pd
import numpy as np

print(f"Pandas version: {pd.__version__}")

Pandas version: 2.3.3

## 1. Creating Data
You can create a **DataFrame** (a table) from dictionaries or lists.

In [2]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
}

df = pd.DataFrame(data)
df.head()

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    David   40     Tokyo

## 2. Basic Exploration
Get a feel for your data's shape and statistics.

In [3]:
print("--- Info ---")
df.info()

print("\n--- Descriptive Stats ---")
display(df.describe())

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

--- Descriptive Stats ---

             Age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

## 3. Selection & Filtering
How to grab specific rows or columns.

In [4]:
# Select a column
ages = df['Age']

# Filter rows where Age > 30
over_30 = df[df['Age'] > 30]
over_30

      Name  Age   City
2  Charlie   35  Paris
3    David   40  Tokyo

## 4. Adding & Modifying Columns
Vectorized operations make this incredibly fast.

In [5]:
# Create a new column based on logic
df['Senior'] = df['Age'] >= 35

# Uppercase the cities
df['City'] = df['City'].str.upper()
df

      Name  Age      City  Senior
0    Alice   25  NEW YORK   False
1      Bob   30    LONDON   False
2  Charlie   35     PARIS    True
3    David   40     TOKYO    True

## 5. Grouping and Aggregation
The 'Split-Apply-Combine' strategy.

In [6]:
# Group by 'Senior' status and find mean age
df.groupby('Senior')['Age'].mean()

Senior
False    27.5
True     37.5
Name: Age, dtype: float64