# Pandas Essentials: A Quick-Start Guide

Pandas is the bread and butter of Python data analysis. This notebook covers the core operations you'll use 90% of the time.

In [19]:
import pandas as pd
import numpy as np

print(f"Pandas version: {pd.__version__}")

Pandas version: 2.3.3

## Creating Data

You can create a **DataFrame** (a table) from dictionaries or lists.

In [20]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 40, 35, 30],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
}

df = pd.DataFrame(data)
df.head()

      Name  Age      City
0    Alice   25  New York
1      Bob   40    London
2  Charlie   35     Paris
3    David   30     Tokyo

## reading and writing CSV

In [21]:
# write df to csv - this will write the 
df.to_csv("fake_data.csv")

# read fake_data to df_in
df_in = pd.read_csv("fake_data.csv", index_col=0)
df_in.head()

      Name  Age      City
0    Alice   25  New York
1      Bob   40    London
2  Charlie   35     Paris
3    David   30     Tokyo

## Basic Exploration
Get a feel for your data's shape and statistics.

In [22]:
print("--- Info ---")
df.info()

print("\n--- Descriptive Stats ---")
display(df.describe())

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

--- Descriptive Stats ---

             Age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

## Column access

Get a single column

In [23]:
# Select a column
ages = df['Age']
ages

0    25
1    40
2    35
3    30
Name: Age, dtype: int64

In [24]:
# get multiple columns
cols = ['Name','City']
name_city = df[cols]
name_city

      Name      City
0    Alice  New York
1      Bob    London
2  Charlie     Paris
3    David     Tokyo

## Sorting & Filtering

In [25]:
# ascending=True is default
sorted_df = df.sort_values('Age', ascending=True)
sorted_df

      Name  Age      City
0    Alice   25  New York
3    David   30     Tokyo
2  Charlie   35     Paris
1      Bob   40    London

In [26]:
# Filter rows where Age > 30
f = (df['Age'] > 30)
over_30 = df[f]
over_30

      Name  Age    City
1      Bob   40  London
2  Charlie   35   Paris

## Adding & Modifying Columns
Vectorized operations make this incredibly fast.

In [27]:
# Create a new column based on logic
f = (df['Age'] >= 35)
df['Senior'] = df[f]

# Uppercase the cities
df['City'] = df['City'].str.upper()
df

ValueError: Cannot set a DataFrame with multiple columns to the single column Senior